version: '3.1'

services:

  db:
    container_name: 'postgres'
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 5432:5432

  adminer:
    container_name: 'adminer'
    image: adminer
    restart: always
    ports:
      - 8080:8080